<!DOCTYPE html>
<html>
<head>
  <title>Washington State K-12 Enrollment</title>
  <meta charset="utf-8">
  <meta name="description" content="Washington State K-12 Enrollment">
  <meta name="author" content="k12eddata">
  <meta name="generator" content="slidify" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/default.css" media="all" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/phone.css" 
    media="only screen and (max-device-width: 480px)" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/slidify.css" >
  <link rel="stylesheet" href="libraries/highlighters/highlight.js/css/solarized_light.css" />
  <base target="_blank"> <!-- This amazingness opens all links in a new tab. -->  <link rel=stylesheet href="./assets/css/ribbons.css"></link>

  
  <!-- Grab CDN jQuery, fall back to local if offline -->
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>
  <script>window.jQuery || document.write('<script src="libraries/widgets/quiz/js/jquery.js"><\/script>')</script> 
  <script data-main="libraries/frameworks/io2012/js/slides" 
    src="libraries/frameworks/io2012/js/require-1.0.8.min.js">
  </script>
  
  

</head>
<body style="opacity: 0">
  <slides class="layout-widescreen">
    
    <!-- LOGO SLIDE -->
        <slide class="title-slide segue nobackground">
  <aside class="gdbar">
    <img src="assets/img/wamap2small.png">
  </aside>
  <hgroup class="auto-fadein">
    <h1>Washington State K-12 Enrollment</h1>
    <h2>A visual comparison by county and school district, 2012-2013</h2>
    <p>k12eddata<br/>Johns Hopkins &quot;Developing Data Products&quot;</p>
  </hgroup>
  <article></article>  
</slide>
    

    <!-- SLIDES -->
    <slide class="" id="slide-1" style="background:;">
  <hgroup>
    <h2>Why We Care about Students</h2>
  </hgroup>
  <article data-timings="">
    <h4><img src="assets/img/question_mark.png" alt="?"> What is significant about Kindergarten - 12th grade (ages 5-18)?</h4>

<p><img src="assets/img/wasealsmall.png" alt="Washington State Seal"> The Washington State Constitution says the state has a paramount duty to educate children.   </p>

<blockquote>
<p>&quot;It is the paramount duty of the state to make ample provision for the education of all children residing within its borders, without distinction or preference on account of race, color, caste, or sex.&quot;  </p>
</blockquote>

<p><a href="http://leg.wa.gov/Senate/Committees/WM/Documents/2014%20K12%20Citizens%20Guide.pdf">Washington Constitution, article IX, section 1</a>  </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-2" style="background:;">
  <hgroup>
    <h2>What we know</h2>
  </hgroup>
  <article data-timings="">
    <h4><img src="assets/img/question_mark.png" alt="?"> How many full-time students are there?</h4>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     9.1   252.0   940.5  3399.0  3444.0 47570.0
</code></pre>

<p><img src="assets/img/student_freepik.png" alt="Student"> In 2012-2013 there were 1002848 students. They spanned 39 counties and 295 school districts.  </p>

<p>There was an extreme distribution of students throughout the state. The mean number of students per school district was <strong>3399</strong>, but the largest school district had <strong>47570</strong> students, and the smallest school district had <strong>9</strong> students.  </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-3" style="background:;">
  <hgroup>
    <h2>How this Application Helps</h2>
  </hgroup>
  <article data-timings="">
    <h4><img src="assets/img/question_mark.png" alt="?"> What can this application help me understand?</h4>

<p><img src="assets/img/devdataprodproject_graphsnip.png" alt="Bar Graph"> It graphically illustrates the scope of student enrollment throughout the state. You can explore individual school district enrollment by county and compare county figures to statewide figures.  </p>

<p><img src="assets/img/devdataprodproject_graph.png" alt="King Co. Enrollment Graph"></p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-4" style="background:;">
  <hgroup>
    <h2>The Future</h2>
  </hgroup>
  <article data-timings="">
    <h4><img src="assets/img/question_mark.png" alt="?"> I want to learn more. Where do I start?</h4>

<p><img src="assets/img/waospiseal.png" alt="Washington State OSPI"> Visit the <a href="http://www.k12.wa.us">Office of Superintendent of Public Instruction</a>. This state office is the custodian of enrollment and financial information for K-12 education.  </p>

<h4><img src="assets/img/question_mark.png" alt="?"> I have ideas on ways to examine the data. How can I help?</h4>

<p><img src="assets/img/email_icon.png" alt="Email"> Email <a href="mailto:k12eddata@gmail.com">k12eddata</a> with suggestions about data enhancements, such as including funding sources and amounts or a graphical geopolitical interface.  </p>

<h5>Thank you for your interest in our children&#39;s future!</h5>

<p>All images are the property of the original owner. These images are used only for educational purposes.  </p>

  </article>
  <!-- Presenter Notes -->
</slide>

    <slide class="backdrop"></slide>
  </slides>
  <div class="pagination pagination-small" id='io2012-ptoc' style="display:none;">
    <ul>
      <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=1 title='Why We Care about Students'>
         1
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=2 title='What we know'>
         2
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=3 title='How this Application Helps'>
         3
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=4 title='The Future'>
         4
      </a>
    </li>
  </ul>
  </div>  <!--[if IE]>
    <script 
      src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js">  
    </script>
    <script>CFInstall.check({mode: 'overlay'});</script>
  <![endif]-->
</body>
  <!-- Load Javascripts for Widgets -->
  
  <!-- LOAD HIGHLIGHTER JS FILES -->
  <script src="libraries/highlighters/highlight.js/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <!-- DONE LOADING HIGHLIGHTER JS FILES -->
   
  </html>